name: Build & Deploy Container Image

on:
  repository_dispatch:
    types: [docker-build]

jobs:
  build-and-push:
    name: Container Build & Registry Push
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java Development Kit
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'liberica'

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Application Artifact
        run: mvn clean package -DskipTests

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/banking-movement-service:latest
            ${{ secrets.DOCKER_USERNAME }}/banking-movement-service:v${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
